#!/bin/bash
wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
bash miniconda.sh -b -p $HOME/miniconda
export PATH="$HOME/miniconda/bin:$PATH"
conda create -n myenv -c conda-forge python=3.10 numpy matplotlib ipykernel -y
$HOME/miniconda/envs/myenv/bin/python -m ipykernel install --user --name=myenv --display-name "Python (myenv)"
